version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: quiz-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27018:27017
    networks:
      - mongo_network
  redis:
    image: redis:latest
    container_name: quiz-redis
    ports:
      - '6379:6379' # Maps Redis port to localhost
    networks:
      - mongo_network

volumes:
  mongodb_data:
    driver: local

networks:
  mongo_network:
    driver: bridge
